# Generated by Django 4.1 on 2022-09-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('name', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('plant_type', models.CharField(max_length=24)),
                ('sun_requirements', models.CharField(choices=[('FS', 'Lots of sunlight.'), ('HS', 'Half sun, half shade.'), ('NS', 'Minimal sunlight.'), ('??', 'Unkown.')], default='??', max_length=2)),
                ('watering_interval', models.DurationField()),
                ('last_watered', models.DateTimeField()),
                ('pokon_interval', models.DurationField()),
                ('last_pokon', models.DateTimeField()),
            ],
        ),
    ]
