# Generated by Django 4.1 on 2022-09-06 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='pokon_interval',
            field=models.DurationField(choices=[(datetime.timedelta(days=30), '1x/month'), (datetime.timedelta(days=15), '2x/month'), (datetime.timedelta(days=7), '1x/week'), (datetime.timedelta(days=4), '2x/week'), (datetime.timedelta(days=1), '1x/day')]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering_interval',
            field=models.DurationField(choices=[(datetime.timedelta(days=30), '1x/month'), (datetime.timedelta(days=15), '2x/month'), (datetime.timedelta(days=7), '1x/week'), (datetime.timedelta(days=4), '2x/week'), (datetime.timedelta(days=1), '1x/day')]),
        ),
    ]
