import Head from 'next/head'
import React from 'react'


export default function Home() {
  const data = ["A", "B", "C"]
  const [token, setToken] = React.useState(Object());

  // useEffect(() => {
  //   login(email, password)
  // }, [email, password])


  return (
    <div className="main">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div>Hello</div>
      <div>{data.map(x => <div>{x}</div>)}</div>
    </div>
  )
}