import Head from 'next/head'
import React, { useState, useEffect } from 'react'
import { signInWithEmailAndPassword } from "firebase/auth";
import auth from './config'


export default function Home() {

  const [email, setEmail] = useState("w.chunheung@gmail.com");
  const [password, setPassword] = useState("F4zCd3HzUdHfGg38HiP24YsByV");

  useEffect(() => {
    login(email, password)
  }, [email, password])

  function handleLoginClick() {
    setEmail()
  }





  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hello</div>
      <form>
        
      </form>
    </>
  )
}


function login(email: string, password: string) {
  signInWithEmailAndPassword(auth, email, password)
  .then((userCredential) => {
    // Signed in 
    console.log(userCredential);
    const user = userCredential.user;
    // ...
  })
  .catch((error) => {
    console.log(error.message);
    const errorCode = error.code;
    const errorMessage = error.message;
    // ..
  });
}