# # This is a basic workflow to help you get started with Actions

# name: Build and Deploy Website

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   Build-and-deploy:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     concurrency:
#       group: ${{ github.workflow }}-${{ github.ref }}

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
#         with:
#           submodules: true
#           fetch-depth: 0

#       - name: Setup Hugo
#         uses: peaceiris/actions-hugo@v2
#         with:
#           hugo-version: 'latest'
#           extended: true

#       # Runs a single command using the runners shell
#       - name: Build site with Hugo
#         run: hugo --minify

#       - name: FTP Deploy
#         uses: SamKirkland/FTP-Deploy-Action@4.3.0
#         with:
#           server: ${{ secrets.DEPLOY_HOST }}
#           username: ${{ secrets.DEPLOY_USERNAME }}
#           password: ${{ secrets.DEPLOY_PASSWORD }}
#           port: ${{ secrets.DEPLOY_PORT}}
#           local-dir: ${{ secrets.DEPLOY_SOURCE}}
#           server-dir: ${{ secrets.DEPLOY_TARGET}}

# name: Deploy to S3
# on:
#   push:
#     branches:    
#       - master
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#       - run: npm install
#       - run: npm run build
#       - run: npm run export
#       - name: Upload artifacts
#         uses: actions/upload-artifact@v1
#         with:
#           name: build_dir
#           path: ./out
#   publish-s3:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/download-artifact@master
#       with:
#         name: build_dir
#         path: ./out
#     - uses: jakejarvis/s3-sync-action@master
#       with:
#         args: --acl public-read --follow-symlinks --delete
#       env:
#         SOURCE_DIR: './out'
#         AWS_REGION: 'us-east-1'
#         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   create-release: 
#     needs: publish-s3
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - uses: smcelhinney/github-create-release-action@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}